"""add geo location

Revision ID: c91f0758b9af
Revises:
Create Date: 2025-12-01 23:00:26.336704

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c91f0758b9af"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "geo_location",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ip", sa.String(), nullable=True),
        sa.Column("ipstack_response", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_geo_location_id"), "geo_location", ["id"], unique=False)
    op.create_index(op.f("ix_geo_location_ip"), "geo_location", ["ip"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geo_location_ip"), table_name="geo_location")
    op.drop_index(op.f("ix_geo_location_id"), table_name="geo_location")
    op.drop_table("geo_location")
    # ### end Alembic commands ###
